### ISSUE TITLE
SYS PI*656 doesn't work, and doesn't give an error

### ISSUE THREAD

**Issue by gardners** [gardners/open-roms#21]
This should currently give a SYNTAX ERROR, because the PI character is not a digit, and the current number parser should reject it.

Of course, it would be great to get the equation parser working so that games that are packed with with the packer that uses this start work without intervention, but at least having an error message instead of crashing would be a start.

**Comment by FeralChild64** [comment]
There is a special workaround implemented for this packer. SYS PI*(any other number) indeed produces SYNTAX ERROR for now.
