### ISSUE TITLE
INST (=SHIFT+DEL) doesn't respect quote mode

### ISSUE THREAD

**Issue by mist64** [gardners/open-roms#38]
If you type the following:

    "<INST>

...you should get an inverted vertical bar. Instead, it is interpreted as an actual "insert".

**Comment by FeralChild64** [comment]
Silly me, I treated SHIFT+DEL the same way as DEL. Fixed in commit https://github.com/FeralChild64/open-roms/commit/c51f10ff46e482f16bc234da372dc6b2af9551e7

**Comment by FeralChild64** [comment]
Fixed in the commit mentioned above.
