### ISSUE TITLE
Typos in two symbols

### ISSUE THREAD

**Issue by mist64** [gardners/open-roms#40]
* The symbol "LDTBL" should actually be called "LDTB1". That's what all sources, including "Mapping the C64" call it.
* The symbol "LXSP" should actually be called "LSXP". This is a typo in "Mapping the C64", which was fixed in "Mapping the C128".

**Comment by FeralChild64** [comment]
Fixed in my branch, commit https://github.com/FeralChild64/open-roms/commit/5fd45f1ece7c60e60212225f069d699ed96d6102

**Comment by FeralChild64** [comment]
Fixed in the commit mentioned above.
