### ISSUE TITLE
MEGA65 Target must not use MAP/EOM in VIC-II setup

### ISSUE THREAD

**Issue by gardners** [gardners/open-roms#43]
The MEGA65 HYPPO now launches a CC65 compiled program when from in the hypervisor mode context to allow the user to select which bitstream to launch, and to allow them to flash new bitstreams.  As it is compiled with CC65, it expects some ROM infrastructure to be present, and directly and indirectly calls a few functions.  The one that is currently causing some grief is $E518 to setup and clear the screen.  The problem is that by placing it in the alternate KERNAL space, the MAP / EOM instructions are used, which erases the Hypervisor's existing memory map. This we probably need for this initialisation routine to be in the normal 8KB KERNAL space. I'll look at other solutions from the hardware side, such as locking the MAP settings for the upper-half of memory when in Hypervisor mode.

**Comment by gardners** [comment]
The fix described in the referenced issue has resolved the problem.

**Comment by FeralChild64** [comment]
Good to know - but the VIC II setup in alternate ROM only saves something like 30 bytes, so it wouldn't be a problem at all to bring it back to the main Kernal ROM.
