### ISSUE TITLE
"BASIC BYTES FREE.\r\r" message doesn't work correctly

### ISSUE THREAD

**Issue by gardners** [gardners/open-roms#5]
The packed message printing routines choke on the message

"BASIC BYTES FREE.\r\r"

The \r's don't get printed. But if the message is shortened to:

"BYTES FREE.\r\r"

Then it works correctly.

Also, when it is BASIC BYTES FREE and malfunctioning, there is a stray cursor block drawn on the screen, which I assume to be connected to the bug somehow.

**Comment by gardners** [comment]
Problem seems to be with printing the carriage returns?

**Comment by gardners** [comment]
Stray cursor block has been fixed, but not the rest of the problem.

**Comment by FeralChild64** [comment]
After the compressed text rework this string does no longer cause any problem.
