### ISSUE TITLE
MEGA65 build: consider using version number

### ISSUE THREAD

**Issue by lgblgblgb** [gardners/open-roms#55]
C65 ROM uses strings like V911008 at offset $16 which is great to detect ROM version number. I think Hyppo uses that to decide what DMA chip revision is to provide. But it's useful for other things as well, to simply tell what version of the ROM is. I guess some similar mechanism of MEGA65 builds of open-roms would be useful. Maybe the string should be start with 'O' instead of 'V' (well, V is for version, 'O' is open-rom, so it's kind of awkward) to decide between C65 and open-roms, also to help to avoid the problem that date string for open-rom is actually numerically less than than C65 ROM's (because of the wraparound at year 2000, but well that fact alone can be used to decide as well). My algorithm to detect for version signature was checking at that offset for letter 'V' and then all numeric chars (for the case that there is nothing there for real, like current open-rom builds).

I'm not sure if it's a useful feature of not, to have, though ...

**Comment by FeralChild64** [comment]
Actually, there already is a way to detect the Open ROMs, no matter whether this is for MEGA65 or other machine - both BASIC and KERNAL contains ID data in places which are free in the original C64 ROMs:

https://github.com/MEGA65/open-roms/blob/master/src/basic/rom_revision/bf52.rom_revision_basic.s
https://github.com/MEGA65/open-roms/blob/master/src/basic/rom_revision/e4b7.rom_revision_kernal.s

I hope we can keep them this way, unless there is some important reason not to use these locations. Just don't depend on CONFIG_ID, they might change without warning (for example, if there are more flavours of MEGA65 build in the future); the "OR" signature means this is Open ROMs.

The "(DEVEL SNAPSHOT)" is being replaced by the build system to something like DEV.200903.FC.1 - which currently means 2020, 09 (September), 03, FeralChild (here 2 or 3 characters shortcuts can be present), 1st published build by this developer that day. But this is temporary, it will change at some point - I just don't even dare calling current build even "0.1 ALPHA".

The DMA chip revision doesn't matter for Open ROMs - it requires MEGA65 DMAgic extension nevertheless, and these allow to specify which DMA list format is being used.

Sure, I can put something constant at offset $16 - just not at this moment, I'm busy with migration from KickAssembler to ACME. It will definitely have to stick to 7 bytes limit, in case someone wants to use Open ROMs with the original C65 internal DOS (currently there is no way to do this, but in the future - who knows).

**Comment by FeralChild64** [comment]
Added version string in commit https://github.com/FeralChild64/open-roms/commit/fc8385b1091c52f50217781546985cd98dc3aa30. Format is as follows:

O - for Open ROMs
YYMMDD - same format as in C65 DOS
YY - two most significant digits of the year number, will be "20" for the foreseeable future

This should be enough for about 7980 years. Please note, that sometimes you might get "OXXXXXXXX" string there (for example, when you just type _make test_mega65_ in the _open-roms_ directory) - it means the date wasn't embedded yet.

Regarding the default DMA list - for Open ROMs it doesn't matter; I'm using only the MEGA65 extended list format and I'm not planning to use the plain C65 DMA format ever - IMHO it should be considered obsolete.

**Comment by FeralChild64** [comment]
Change was merged to the main branch some time ago.
