### ISSUE TITLE
Wrong register loaded into STAL+1

### ISSUE THREAD

**Issue by mist64** [gardners/open-roms#66]
src/kernal/iostack/f4a5.load.s:
```
	; Store start address of LOAD
	lda MEMUSS+0
	sta STAL+0
	lda MEMUSS+1
	sty STAL+1
```

See https://github.com/commanderx16/x16-rom/pull/174

**Comment by FeralChild64** [comment]
Thank you - fixed in my development branch:

https://github.com/FeralChild64/open-roms/commit/7510d4a83f0a3abc0c0403d7e57afe10460fa4a9

**Comment by FeralChild64** [comment]
Bugfix merged to master.
