### ISSUE TITLE
Palette initialisation on the MEGA65

### ISSUE THREAD

**Issue by gardners** [gardners/open-roms#68]
The MEGA65 calls the OpenROM setup routine as part of its flash menu initialisation on boot.  The MEGA65 has already established the palette it wants at that point, but OpenROMs replace the palette, an in particular, clear the palette entries $10-$FF that are used for the boot banner, causing it to appear with wrong colours.

Maybe the easiest solution is to remove the code for MEGA65 palette setup that erases the palette before setting the base 16 colours?

**Comment by FeralChild64** [comment]
Could you try if binary:

https://github.com/FeralChild64/open-roms/blob/master/bin/mega65.rom

fixes the problem? BTW, please do not distribute this particular binary with MEGA65, as the internal DOS implementation is in the process of rework, it might cause problems. If the solution works, I'll either prepare a hotfix release, or make sure the DOS works first.
