### ISSUE TITLE
Trouble compiling under Debian 11: failed to open 'build/target_generic.rombuild/chargen_pxlfont/OUTx_x.BIN': No such file or directory

### ISSUE THREAD

**Issue by daitangio** [gardners/open-roms#71]
Hi, i have trouble compiling under Debian 11 the test_generic
I got:

```
$ make test_generic
dd: failed to open 'build/target_generic.rombuild/chargen_pxlfont/OUTx_x.BIN': No such file or directory
make: *** [Makefile:619: build/kernal_generic.rombuild/chargen_pxlfont.rom] Error 1
```
Software versions:
```
$ gcc --version
gcc (Debian 10.2.1-6) 10.2.1 20210110
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ ./build/tools/acme  --version
This is ACME, release 0.97 ("Zem"), 30 Jul 2020
  Platform independent version.
```

The make all command seems to work.
How can I fix it?
Thank you!

**Comment by FeralChild64** [comment]
At first glance looks like broken dependencies in the makefile - I’ll look at this, just not today.

It might be easier to just launch VICE and load appropriate ROMs. The emulator has changed some time ago, binaries are now named differently, so this target might not work as expected nevertheless.

**Comment by Compyx** [comment]
If you're referring to the ROM names, they have indeed been renamed since the 3.7 release to include their part number. For C64 you can look at `c64rom.h`: https://sourceforge.net/p/vice-emu/code/HEAD/tree/trunk/vice/src/c64/c64rom.h
Other emulators have similar `*rom.h` files with the new names.

**Comment by FeralChild64** [comment]
I mean:
- long time ago the executable was called `x64`
- later `x64sc` appeared, a slower, but more precise emulator
- later `x64` disappeared
- now I see `x64sc.sdl` and `x64sc.gtk` executables, `x64sc` is gone, there is not even a symlink for compatibitilty

This is not fun at all if you try to embed the emulator in your toolchain.

**Comment by Compyx** [comment]
None of our distributions use `x64sc.sdl` or `x64sc.gtk` for binary names and we've never used that naming scheme. What Linux distro does this? Debian appears to use plain `x64sc` (`apt-file list vice` tells me this on Debian 11.6).

If you're looking for Debian packages, we provide those since 3.7: https://github.com/VICE-Team/svn-mirror/releases
The packages are called `gtk3vice`, `sdl2vice` and `headlessvice` and conflict with the Debian-provided `vice` package and each other, specifically since I didn't want to use any UI prefix or suffix for the binaries.

**Comment by FeralChild64** [comment]
@daitangio  Commit https://github.com/MEGA65/open-roms/commit/11ba7d19abbd7f3cfe42fe2bfd2a595088e05bc1 should fix the problem, can you confirm?

@Compyx I'm using Gentoo. It seems they altered. OK, sorry for misinformation - it's the current Gentoo ebuild ([this line](https://gitweb.gentoo.org/repo/gentoo.git/tree/app-emulation/vice/vice-3.7.1.ebuild#n114)) changed binary names, to allow GTK+ and SDL binaries to coexist in the same system.

**Comment by daitangio** [comment]
> @daitangio Commit [11ba7d1](https://github.com/MEGA65/open-roms/commit/11ba7d19abbd7f3cfe42fe2bfd2a595088e05bc1) should fix the problem, can you confirm?

Confirmed now I get an error about missing x64sc which is fine:

`$ make test_generic
x64sc -kernal build/kernal_generic.rom -basic build/basic_generic.rom -chargen build/chargen_pxlfont.rom -moncommands build/symbols_generic.vs -1 testsuite/testtape-c64-pal-turbo.tap -8 testsuite/testdisk.d64
make: x64sc: No such file or directory
make: *** [Makefile:846: test_generic] Error 127
`
