### ISSUE TITLE
token search routine goes funny at TAB(

### ISSUE THREAD

**Issue by gardners** [gardners/open-roms#9]
All keywords after TAB( when displayed are wrong.

To reproduce, type the keyword in direct mode on a line by itself. It should echo back out verbatim.

**Comment by gardners** [comment]
Fixed page-wrap problem.

Now most tokens work, except oddly (and perhaps cooincidentally) TAB( doesn't match.

Verify all others, and figure out cause.

**Comment by gardners** [comment]
Position in the list doesn't seem to affect it.
Also all the single-character math operators and relational operators don't get detected.

**Comment by gardners** [comment]
Also confirmed it is not the word boundary check that it is failing.  It just seems to not match it.
However the string it compresses to matches what compress_text.c compressed it to originally.
Presumably there is some subtle bug in there.

The math operators might be getting too many end byte sequences on the end of their sequences in pack_word.

**Comment by FeralChild64** [comment]
Since the bug report was issued, the tokeniser has been rewritten. Current one seems to handle "TAB(" correctly (produces same results as original C64 ROM tokeniser), display issues seems to be solved too.
